# Flask config values.
flask_cfg:
  # Turn this on for debug mode.
  DEBUG: false

# The base directory for Skier.
base_directory: /var/skier

# The path for the PGP keyring to be stored.
pgp_keyring_path: /var/skier/keyring

# The redis database info.
redis:
  host: localhost
  port: 6379
  db: 1

# The hostname for the server.
hostname: pgp.example.com

# The SKS keyservers to allow importing from.
sks_imports:
  - pgp.mit.edu
  - sks.gpg.im

# The Skier keyservers to allow importing from.
skier_imports:
 - pgp.sundwarf.me

# Discovery section.
discovery:
  # The length of the string to stop single-thread discovering under (less-than equals).
  length_limit: 4
  # The timeout before a new discovery for the same string can be launched.
  timeout: 300