# Flask config values.
flask_cfg:
  # Turn this on for debug mode.
  DEBUG: true

# The path for the PGP keyring to be stored.
pgp_keyring_path: /var/skier/keyring

# The redis database info.
redis:
  host: localhost
  port: 6379
  db: 1

abc: def