"""Database stuff.

Revision ID: c4f76daa60
Revises: 477282e71b9
Create Date: 2015-08-19 22:45:16.217715

"""

# revision identifiers, used by Alembic.
revision = 'c4f76daa60'
down_revision = '477282e71b9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pgp_keyid', sa.String(length=16), nullable=False),
    sa.Column('sigtype', sa.Integer(), nullable=True),
    sa.Column('key_sfp_for', sa.String(length=16), nullable=True),
    sa.Column('key_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['key_id'], ['key.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('key', sa.Column('subkeys', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    op.alter_column('key', 'armored',
               existing_type=sa.TEXT(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('key', 'armored',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('key', 'subkeys')
    op.drop_table('signature')
    ### end Alembic commands ###
