"""Initial DB migration.

Revision ID: 45fdf20fb2f
Revises: None
Create Date: 2015-08-18 22:42:30.701921

"""

# revision identifiers, used by Alembic.
revision = '45fdf20fb2f'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('fingerprint', sa.String(length=40), nullable=False),
    sa.Column('key_fp_id', sa.String(length=8), nullable=False),
    sa.Column('keyalgo', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('armored', sa.Text(), nullable=False),
    sa.Column('subkeys', postgresql.ARRAY(sa.String(length=255)), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pgp_keyid', sa.String(length=16), nullable=False),
    sa.Column('sigtype', sa.String(length=16), nullable=True),
    sa.Column('key_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['key_id'], ['key.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signature')
    op.drop_table('key')
    ### end Alembic commands ###
