"""Add OID field to db

Revision ID: 2e82d01dc7d
Revises: c4f76daa60
Create Date: 2015-08-23 20:11:10.462088

"""

# revision identifiers, used by Alembic.
revision = '2e82d01dc7d'
down_revision = 'c4f76daa60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key', sa.Column('oid', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('key', 'oid')
    ### end Alembic commands ###
