"""Add Synch field.

Revision ID: 477282e71b9
Revises: 376c313a482
Create Date: 2015-08-19 16:18:01.600453

"""

# revision identifiers, used by Alembic.
revision = '477282e71b9'
down_revision = '376c313a482'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('synch_time', sa.DateTime(), nullable=False),
    sa.Column('synch_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('synch')
    ### end Alembic commands ###
